name: Fhi.HelseId.Demo.CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      client-directory: ./ClientApp


    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm install
      working-directory: ${{env.client-directory}}
    - name: Build Angular frontend
      run: npm run build
      working-directory: ${{env.client-directory}}


